<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\HaleyProject\HaleyVersion.Props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SignAssembly>true</SignAssembly>
	<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
	<AssemblyOriginatorKeyFile>HaleyProject.snk</AssemblyOriginatorKeyFile>
	<RootNamespace>Haley.Log</RootNamespace>
	<AssemblyName>Haley.Log</AssemblyName>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<Product>Haley Logger</Product>
	<Description>A simple logger based on .Net Standard to integrate in C# projects. Helps to export the log to different formats including txt, json, xml</Description>
	<Version>$(HaleyLogVersion)</Version>
	<AssemblyVersion>2.0.0.0</AssemblyVersion>
	<PackageReleaseNotes>Prevents duplicate provider registration, preserves ILogger exceptions, and implements date-based file rollover through ShouldGenerateEachDay.
    </PackageReleaseNotes>
	<FileVersion>2.0.0.0</FileVersion>
	<PackageIcon>Haley.png</PackageIcon>
	  <IncludeSymbols>true</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<WarningLevel>2</WarningLevel>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Haley.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <Import Project="$(SolutionDir)ProjectReferences_$(SolutionName).txt" Condition="Exists('$(SolutionDir)ProjectReferences_$(SolutionName).txt')" />
	<Choose>
    <When Condition="Exists($(HaleyExtensions))">
      <ItemGroup>
        <ProjectReference Include="$(HaleyExtensions)\HaleyExtensions.csproj">
          <Name>HaleyExtensions</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
     <ItemGroup>
       <PackageReference Include="Haley.Extensions" Version="$(HaleyExtensionsVersion)" />
	 </ItemGroup>
    </Otherwise>
</Choose>  
</Project>
